import shutil
from datetime import date

from dataeng.scale.generate_dataset import generate_scale_dataset
from dataeng.scale.scale_test import run_partition_pruning_benchmark


def test_generate_and_benchmark_small_dataset_returns_correct_counts(tmp_path):
    """Not a performance assertion (timings are environment-dependent) —
    this checks that all three query strategies (full scan, glob+filter,
    direct partition path) agree on the actual data: same total, same
    per-partition count. The real, large-scale timing numbers this module
    is built to measure are reported in the README, generated by running
    this module directly against the full 182.5M-row dataset."""
    out_dir = str(tmp_path / "scale_small")
    n_symbols, n_days, rows_per_partition = 3, 3, 100

    gen_result = generate_scale_dataset(
        out_dir,
        n_symbols=n_symbols,
        n_days=n_days,
        rows_per_partition=rows_per_partition,
        start_date=date(2024, 1, 1),
    )
    assert gen_result.total_rows == n_symbols * n_days * rows_per_partition

    try:
        report = run_partition_pruning_benchmark(out_dir, target_symbol="SYM-001", target_date="2024-01-02")
        assert report.total_rows_in_dataset == gen_result.total_rows
        assert report.total_files == n_symbols * n_days

        for timing in (report.polars_full_scan, report.duckdb_full_scan):
            assert timing.row_count == gen_result.total_rows

        for timing in (
            report.polars_glob_filter,
            report.polars_direct_partition,
            report.duckdb_glob_filter,
            report.duckdb_direct_partition,
        ):
            assert timing.row_count == rows_per_partition
    finally:
        shutil.rmtree(tmp_path, ignore_errors=True)
