global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: posttrade_ingestor
    static_configs:
      - targets: ["host.docker.internal:9100"]
        labels:
          component: ingestor

  - job_name: posttrade_workers
    static_configs:
      - targets:
          - "host.docker.internal:9101"
          - "host.docker.internal:9102"
          - "host.docker.internal:9103"
          - "host.docker.internal:9104"
        labels:
          component: worker
