from datetime import datetime
from decimal import Decimal

from pydantic import BaseModel, ConfigDict

from posttrade.models.enums import Side


class Fill(BaseModel):
    """A synthetic execution generated by the trade book simulator (Phase 5).

    `is_planted_anomaly` and `anomaly_type` are ground truth set by the
    simulator itself when it deliberately injects a break — used in Phase 7
    to score the reconciler's actual precision/recall, not just eyeball it.

    `sequence` is the true per-symbol execution order, independent of
    `timestamp` — the unmatched_fill anomaly deliberately corrupts timestamp,
    so position-drift math must never derive execution order from it.
    """

    model_config = ConfigDict(frozen=True)

    fill_id: str
    order_id: str
    symbol: str
    sequence: int
    price: Decimal
    quantity: Decimal
    side: Side
    timestamp: datetime
    is_planted_anomaly: bool = False
    anomaly_type: str | None = None
